### ISSUE TITLE
git-lfs pull failed

### ISSUE THREAD

**Issue by beyond2002** [netgroup/srv6-calico-vpp-tests#1]
$ git-lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/netgroup/srv6-calico-vpp-tests.git/info/lfs'

**Comment by zvfvrv** [comment]
Hi @beyond2002, thanks for pointing it out,  I am working on a fix to avoid the use of git-lfs.  I will provide the fix very soon

**Comment by zvfvrv** [comment]
Hi @ beyond2002, the repository no longer uses git-lfs. please let me know if it works now.

**Comment by beyond2002** [comment]
Everything goes well until "make start-scenario1".

The error message as following:

Create veth pair with srv6-calico-vpp-tests_master
../scripts/create-veth-pair.sh r3 0 srv6-calico-vpp-tests_master srv6-calico-vpp-tests fd10::1020/64 192.168.10.3/24
srv6-calico-vpp-tests0 virbr-tests0
Create veth pair inside 68820
Set vethr30 up
Set vethr30 to virbr-tests0
Set vethr30 to up inside the NS
Create veth pair with srv6-calico-vpp-tests_worker1
../scripts/create-veth-pair.sh r3 1 srv6-calico-vpp-tests_worker1 srv6-calico-vpp-tests fd11::1020/64 192.168.11.3/24
srv6-calico-vpp-tests1 virbr-tests1
Create veth pair inside 68820
Set vethr31 up
Set vethr31 to virbr-tests1
Set vethr31 to up inside the NS
Create veth pair with srv6-calico-vpp-tests_worker2
../scripts/create-veth-pair.sh r8 2 srv6-calico-vpp-tests_worker2 srv6-calico-vpp-tests fd12::1020/64 192.168.12.3/24
srv6-calico-vpp-tests2 virbr-tests2
Create veth pair inside 68840
Set vethr82 up
Set vethr82 to virbr-tests2
Set vethr82 to up inside the NS
make[2]: Leaving directory '/home/vyos/srv6-calico-vpp-tests/scenario1'
make[2]: Entering directory '/home/vyos/srv6-calico-vpp-tests/scenario1'
Add routes localsids with srv6-calico-vpp-tests_master
../scripts/add-route-localsids.sh r3 0 srv6-calico-vpp-tests_master srv6-calico-vpp-tests fcdd:0:0:aa::/64 fd10::1000
srv6-calico-vpp-tests0 virbr-tests0 fcdd:0:0:aa::/64 fd10::1000
RTNETLINK answers: No route to host
make[2]: *** [Makefile:41: add-routes-localsids-scenario] Error 2
make[2]: Leaving directory '/home/vyos/srv6-calico-vpp-tests/scenario1'
make[1]: *** [Makefile:70: start-scenario1] Error 2
make[1]: Leaving directory '/home/vyos/srv6-calico-vpp-tests/scenario1'
make: *** [Makefile:65: start-scenario1] Error 2
